#!/bin/bash
set -e

HTTP_PORT=${HTTP_PORT:-4000}
GODOC_PORT=${GODOC_PORT:-6060}

COMMIT="$(git rev-parse --short HEAD)"

#use CompileDaemon to auto-rebuild
#set path in compiledeamon
SITE=github.com
USER=fschl
REPO=glide
MAIN_FILE=glide.go

PATH_TO_WATCH=$GOPATH"/src/$SITE/$USER/$REPO"
BUILD_CMD="go install $PATH_TO_WATCH"
FOLLOW_CMD="go run "$PATH_TO_WATCH"/"$MAIN_FILE

echo "run the deamon... "
cd /go/bin/
./CompileDaemon -directory="$PATH_TO_WATCH" -build="$BUILD_CMD" -recursive=true -command="$FOLLOW_CMD" -color=true
